/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef Hello_CONSTANTS_H
#define Hello_CONSTANTS_H

#include "Hello_types.h"

namespace Demo {

class HelloConstants {
 public:
  HelloConstants();

};

extern const HelloConstants g_Hello_constants;

} // namespace

#endif
