/**
 * Autogenerated by Thrift Compiler (0.12.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "Hello_constants.h"

namespace Demo {

const HelloConstants g_Hello_constants;

HelloConstants::HelloConstants() {
}

} // namespace

